#!/usr/bin/env python3
import argparse
import os
import sys
import time
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Optional

from playwright.sync_api import sync_playwright


YOUTUBE_WARMUP_URLS = [
    "https://www.youtube.com/robots.txt",
    "https://www.youtube.com/",
]


def log(msg: str) -> None:
    ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    print(f"[{ts}] {msg}", flush=True)


def is_expired(expires_raw: str) -> bool:
    try:
        exp = int(expires_raw)
    except Exception:
        return False
    if exp <= 0:
        return False
    return exp < int(time.time())


def parse_netscape_cookies(path: Path) -> List[Dict]:
    cookies: List[Dict] = []
    if not path.exists():
        raise FileNotFoundError(f"cookies file not found: {path}")

    with path.open("r", encoding="utf-8", errors="replace") as f:
        for raw_line in f:
            line = raw_line.strip()
            if not line or line.startswith("#"):
                continue

            parts = raw_line.rstrip("\n").split("\t")
            if len(parts) != 7:
                continue

            domain, include_subdomains, path_str, secure_str, expires_str, name, value = parts

            if is_expired(expires_str):
                continue

            cookie: Dict = {
                "name": name,
                "value": value,
                "domain": domain,
                "path": path_str or "/",
                "secure": secure_str.upper() == "TRUE",
                "httpOnly": False,
            }

            # Session cookie in Netscape format is often 0.
            try:
                expires = int(expires_str)
                if expires > 0:
                    cookie["expires"] = expires
            except Exception:
                pass

            # Best-effort SameSite guess; omitted if unknown.
            cookies.append(cookie)

    return cookies


def export_netscape_cookies(cookies: List[Dict], out_path: Path, domain_filter: Optional[str] = None) -> int:
    out_path.parent.mkdir(parents=True, exist_ok=True)

    kept = []
    for c in cookies:
        domain = c.get("domain", "")
        if domain_filter and domain_filter not in domain:
            continue
        kept.append(c)

    with out_path.open("w", encoding="utf-8", newline="\n") as f:
        f.write("# Netscape HTTP Cookie File\n")
        f.write("# This file was generated by Playwright.\n")
        f.write("# https://curl.se/docs/http-cookies.html\n\n")
        for c in kept:
            domain = c.get("domain", "")
            include_subdomains = "TRUE" if domain.startswith(".") else "FALSE"
            path_str = c.get("path", "/")
            secure = "TRUE" if c.get("secure", False) else "FALSE"
            expires = c.get("expires", 0)
            try:
                expires = int(expires)
            except Exception:
                expires = 0
            name = c.get("name", "")
            value = c.get("value", "")
            f.write(f"{domain}\t{include_subdomains}\t{path_str}\t{secure}\t{expires}\t{name}\t{value}\n")

    return len(kept)


def backup_file(path: Path) -> Optional[Path]:
    if not path.exists():
        return None
    stamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    backup = path.with_name(f"{path.stem}.{stamp}{path.suffix}")
    backup.write_bytes(path.read_bytes())
    return backup


def refresh_once(
    input_cookies: Path,
    output_cookies: Path,
    profile_dir: Path,
    channel: Optional[str],
    executable_path: Optional[str],
    headless: bool,
    warmup_wait_ms: int,
    backup: bool,
    extra_url: Optional[str],
) -> None:
    cookies = parse_netscape_cookies(input_cookies)
    if not cookies:
        raise RuntimeError("No valid cookies loaded from input file")

    if backup and output_cookies.exists():
        backup_path = backup_file(output_cookies)
        if backup_path:
            log(f"Backed up old output cookies to: {backup_path}")

    profile_dir.mkdir(parents=True, exist_ok=True)

    launch_kwargs = {
        "user_data_dir": str(profile_dir),
        "headless": headless,
        "args": [
            "--disable-blink-features=AutomationControlled",
            "--lang=en-US",
        ],
    }
    if channel:
        launch_kwargs["channel"] = channel
    if executable_path:
        launch_kwargs["executable_path"] = executable_path

    with sync_playwright() as p:
        context = p.chromium.launch_persistent_context(**launch_kwargs)
        try:
            page = context.new_page()

            # Seed initial cookies into the context.
            context.add_cookies(cookies)
            log(f"Injected {len(cookies)} cookies into browser context")

            # Warm up YouTube pages so the browser can receive updated Set-Cookie values.
            urls = list(YOUTUBE_WARMUP_URLS)
            if extra_url:
                urls.append(extra_url)
            for url in urls:
                try:
                    log(f"Opening: {url}")
                    page.goto(url, wait_until="domcontentloaded", timeout=60000)
                    page.wait_for_timeout(warmup_wait_ms)
                except Exception as e:
                    log(f"Warning: failed to open {url}: {e}")

            # Also perform one context-linked request; Set-Cookie from this request updates the context automatically.
            try:
                resp = context.request.get("https://www.youtube.com/robots.txt", timeout=60000)
                log(f"Context request status for robots.txt: {resp.status}")
            except Exception as e:
                log(f"Warning: context request failed: {e}")

            all_cookies = context.cookies()
            count = export_netscape_cookies(all_cookies, output_cookies, domain_filter="youtube.com")
            log(f"Exported {count} youtube.com cookies to: {output_cookies}")
        finally:
            context.close()


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Periodically refresh YouTube cookies.txt by loading an initial Netscape cookies.txt into a Chromium profile and re-exporting updated cookies."
    )
    parser.add_argument("--input-cookies", required=True, help="Initial Netscape cookies.txt file")
    parser.add_argument("--output-cookies", required=True, help="Path to write refreshed cookies.txt")
    parser.add_argument("--profile-dir", default="./pw-youtube-profile", help="Dedicated Playwright Chromium user data dir")
    parser.add_argument("--channel", default=None, help="Browser channel, e.g. chrome, msedge, chromium")
    parser.add_argument("--executable-path", default=None, help="Explicit browser executable path")
    parser.add_argument("--interval-minutes", type=float, default=0, help="Run every N minutes; 0 means run once")
    parser.add_argument("--headless", action="store_true", help="Run browser headless")
    parser.add_argument("--warmup-wait-ms", type=int, default=4000, help="Wait after each page open")
    parser.add_argument("--extra-url", default=None, help="Optional extra YouTube URL to open before export")
    parser.add_argument("--no-backup", action="store_true", help="Do not backup existing output cookies before overwrite")

    args = parser.parse_args()

    input_cookies = Path(args.input_cookies).expanduser().resolve()
    output_cookies = Path(args.output_cookies).expanduser().resolve()
    profile_dir = Path(args.profile_dir).expanduser().resolve()

    if not input_cookies.exists():
        print(f"Input cookies file does not exist: {input_cookies}", file=sys.stderr)
        return 2

    backup = not args.no_backup

    while True:
        try:
            refresh_once(
                input_cookies=input_cookies,
                output_cookies=output_cookies,
                profile_dir=profile_dir,
                channel=args.channel,
                executable_path=args.executable_path,
                headless=args.headless,
                warmup_wait_ms=args.warmup_wait_ms,
                backup=backup,
                extra_url=args.extra_url,
            )
        except KeyboardInterrupt:
            log("Stopped by user")
            return 130
        except Exception as e:
            log(f"Refresh failed: {e}")

        if args.interval_minutes <= 0:
            break

        sleep_seconds = max(1, int(args.interval_minutes * 60))
        log(f"Sleeping for {sleep_seconds} seconds before next refresh")
        time.sleep(sleep_seconds)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
